//
//  BookContentInteractor.swift
//  ARGBookUI
//
//  Created by Sergei Polshcha on 09.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookContentBusinessLogic
{
  func doSomething(request: BookContent.Something.Request)
}

protocol BookContentDataStore
{
  //var name: String { get set }
}

class BookContentInteractor: BookContentBusinessLogic, BookContentDataStore
{
  var presenter: BookContentPresentationLogic?
  var worker: BookContentWorker?
  //var name: String = ""
  
  // MARK: Do something
  
  func doSomething(request: BookContent.Something.Request)
  {
    worker = BookContentWorker()
    worker?.doSomeWork()
    
    let response = BookContent.Something.Response()
    presenter?.presentSomething(response: response)
  }
}
