//
//  BookContentPresenter.swift
//  ARGBookUI
//
//  Created by Sergei Polshcha on 09.10.2020.
//  Copyright (c) 2020 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol BookContentPresentationLogic
{
  func presentSomething(response: BookContent.Something.Response)
}

class BookContentPresenter: BookContentPresentationLogic
{
  weak var viewController: BookContentDisplayLogic?
    
  // MARK: Do something
  
  func presentSomething(response: BookContent.Something.Response)
  {
    let viewModel = BookContent.Something.ViewModel()
    viewController?.displaySomething(viewModel: viewModel)
  }
    
}
